# Generated by Django 3.1.7 on 2021-03-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='marks',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
